// SETTINGS ACTION TYPES:

export const LANGUAGE = 'LANGUAGE'
export const GENDER = 'GENDER'
export const DOMAIN_CHANGED = 'DOMAIN_CHANGED'
export const CATEGORY_CHANGED = 'CATEGORY_CHANGED'
export const CATEGORY_TREE = 'CATEGORY_TREE'
export const LOCATION = 'LOCATION'
export const PROMOS_LIST = 'PROMOS_LIST'

// USER ACTION TYPES:

export const USER_SIGNED = 'USER_SIGNED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_INIT = 'USER_INIT'
export const USER_UPDATED = 'USER_UPDATED'

// MANNEQUIN ACTION TYPES:

export const LAYER_ACTIVATED = 'LAYER_ACTIVATED'
export const BODY_ACTIVATED = 'BODY_ACTIVATED'
export const ITEM_CHANGED = 'ITEM_CHANGED'
export const MANN_UPDATED = 'MANN_UPDATED'
export const MANN_ACTIVATED = 'MANN_ACTIVATED'
export const DATA_UPDATED = 'DATA_UPDATED'

export const RESOURCES_SET = 'RESOURCES_SET'
export const RESOURCE_CHANGED = 'RESOURCE_CHANGED'

// SOCIAL ACTION TYPES:
export const MANN_SOC_ACTION = 'MANN_SOC_ACTION'
export const USER_SOC_ACTION = 'USER_SOC_ACTION'
